### PR TITLE
Adding README.md on Cheating Sheet for Linux

### PR DESCRIPTION
**Pull request by samuelnan**

### CODE REVIEW

**Comment by huskypower** [comment]
Hi Sam , thank you for your contribution , please submit your commit on the new branch 1-0-stable. Looking forward to your submission in new branch.

**Comment by ytbryan** [comment]
Tim, @huskypower Samuel is committing to the right branch cc @samuelnan

**Comment by huskypower** [comment]
@samuelnan My sincere apology for the last message about the new branch you are on the right track and I will merge your commit , thank you so much for your contribution and kind understanding.

**Review by huskypower — APPROVED** [review]
Hi Sam , thanks for the contribution , commit is merged.

**Comment by samuelnan** [comment]
Thanks Timothy.
Thanks Bryan.


Sent from Yahoo Mail for iPhone


On Wednesday, April 28, 2021, 15:35, Timothy Tan ***@***.***> wrote:




@huskypower approved this pull request.

Hi Sam , thanks for the contribution , commit is merged.

**Review by vishnuaq1 — COMMENTED** [review]
GitHub is going mi**les @ educating **_tq_****

**Pull request merged**
