### PR TITLE
Added Python CheatSheet

### PR DESCRIPTION
**Pull request by hptchris**

### CODE REVIEW

**Comment by shankjs** [comment]
That's a very useful find of the python cheatsheet! Nice!

**Review by shankjs — APPROVED** [review]

**Comment by hadibolehjadi** [comment]
Alamak Shanks! Christine hasn't resolved the pycharm sub that she took out to be standalone instead of under Python. 
No worries tho I'll edit it back!

**Comment by shankjs** [comment]
@hadibolehjadi sorry dude must have over looked it. thanks alot! for the edit

**Review by vishnuaq1 — COMMENTED** [review]
**git clean 
Git is very interesting **

**Pull request merged**
